-- 총동연이 동아리 가입 링크(모집 링크·부원 초대)를 강제 폐기한 이벤트를 남긴다.
-- JOIN_LINK_FORCE_REVOKED: reason=강제 폐기 사유(필수). 운영진 수동 폐기(JOIN_LINK_REVOKED)와
-- 종류를 나누는 이유는 "누가 끊었는지"가 이력의 핵심이기 때문이다 — 행위자 id 만으로는 화면이 구분할 수 없다.
-- 이벤트 종류를 늘릴 때는 CHECK 도 함께 갱신한다(V102 절차 주석, V104·V105·V116·V127·V128 선례).
ALTER TABLE club_audit_event DROP CONSTRAINT club_audit_event_event_type_check;
ALTER TABLE club_audit_event ADD CONSTRAINT club_audit_event_event_type_check CHECK (event_type IN (
    'JOIN_LINK_CREATED', 'JOIN_LINK_REGENERATED', 'JOIN_LINK_REVOKED',
    'JOIN_REQUEST_CREATED', 'JOIN_REQUEST_APPROVED', 'JOIN_REQUEST_REJECTED',
    'RECRUITMENT_FORCE_CLOSED', 'APPLICATION_VIEWED',
    'FEE_POLICY_CREATED', 'FEE_POLICY_UPDATED', 'FEE_POLICY_DELETED',
    'FEE_BILL_ISSUED', 'FEE_BILL_CANCELLED',
    'FEE_PAYMENT_RECORDED', 'FEE_PAYMENT_VOIDED',
    'FEE_TX_MANUAL_MATCHED', 'FEE_TX_IGNORED', 'FEE_TX_UNMATCHED',
    'FEE_ACCOUNT_REGISTERED', 'FEE_ACCOUNT_UPDATED', 'FEE_ACCOUNT_DELETED',
    'FEE_ADMIN_DETAIL_VIEWED', 'FEE_ADMIN_CSV_DOWNLOADED',
    'SECURED_TARGET_CHANGED',
    'CLUB_STATUS_CHANGED', 'CLUB_CLOSED',
    'MEMBER_PHONE_VIEWED', 'MEMBER_LIST_EXPORTED',
    'JOIN_LINK_FORCE_REVOKED'));
