ALTER TABLE notice
    ADD COLUMN IF NOT EXISTS event_start_at  TIMESTAMP    NULL,
    ADD COLUMN IF NOT EXISTS event_end_at    TIMESTAMP    NULL,
    ADD COLUMN IF NOT EXISTS location        VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS host            VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS audience        VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS body_image_urls TEXT[]       NOT NULL DEFAULT '{}';
