package com.duing.domain.notification.entity;

public enum NotificationType {
    RECRUITMENT_OPENED,
    RECRUITMENT_DEADLINE,
    INTERVIEW_SCHEDULED,
    INTERVIEW_UPDATED,
    INTERVIEW_CANCELLED,
    INTERVIEW_AVAILABILITY_REQUESTED,
    INTERVIEW_REMINDER,
    NOTICE_TARGETED,
    FEE_PAID_CONFIRMED,
    FEE_PARTIAL_PAYMENT_CONFIRMED,
    FEE_BILL_OVERDUE,
    FEE_BILL_ISSUED,
    FEE_BILL_DUE_SOON,
    FEDERATION_INQUIRY_RECEIVED,
    FEDERATION_INQUIRY_ANSWERED,
    FEDERATION_INQUIRY_CLOSED,
    FACILITY_BOOKING_SUBMITTED,
    FACILITY_BOOKING_APPROVED,
    FACILITY_BOOKING_REJECTED,
    FACILITY_BOOKING_CONFIRMED,
    FACILITY_BOOKING_CONFLICT,
    FACILITY_BOOKING_CANCELLED
}
