package com.duing.domain.notification.entity;

public enum NotificationType {
    RECRUITMENT_OPENED,
    RECRUITMENT_DEADLINE,
    INTERVIEW_SCHEDULED,
    INTERVIEW_UPDATED,
    INTERVIEW_CANCELLED,
    INTERVIEW_AVAILABILITY_REQUESTED,
    INTERVIEW_REMINDER,
    NOTICE_TARGETED,
    FEE_PAID_CONFIRMED,
    FEE_PARTIAL_PAYMENT_CONFIRMED,
    FEE_BILL_OVERDUE
}
